[project]
name = "sbtr"
version = "0.1.0"
requires-python = "==3.11.*"
dependencies = [
    "biopython==1.87",
    "huggingface-hub==1.11.0",
    "matplotlib==3.10.8",
    "numpy==2.4.3",
    "pandas==3.0.2",
    "plotly==6.7.0",
    "scipy==1.17.1",
    "torch==2.11.0",
    "torchmetrics==1.9.0",
    "tqdm==4.67.3",
    "transformers==5.6.1",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true