"""
Parameter inference for the HIV sequence generator.

Option 1: Generative model — infer statistical parameters from real CRFs,
          then sample new blueprint structures at generation time.
          Allows the model to encounter novel breakpoint configurations.

    Chosen distributions:
    Negative binomial for number of breakpoints
    The number of breakpoints per CRF is a count variable (non-negative integer), so we need a discrete distribution.
    The simplest choice would be Poisson, but Poisson has a hard constraint that mean = variance.
    The negative binomial adds a dispersion parameter that decouples mean and variance.
    If we fit it and find variance ≈ mean, it degrades toward Poisson.

    Log-normal for regular segment lengths (diagnostic only — not used in generation)
    Segment lengths are positive continuous values with a right-skewed distribution. Most segments are short to moderate,
    but some are very long (a single subtype dominating most of the genome).
    NOTE: segment lengths are fully determined by the number of breakpoints and their sampled positions, so this
    distribution is not used in generation — it is inferred and printed only for comparison against generated data.

    Empirical PMF for number of distinct subtypes
    The number of distinct subtypes per CRF is a small discrete variable with a very constrained range (2 to 6).
    Hence we are just using the observed frequencies directly.

    Compound segments as breakpoint-uncertainty zones
    A compound segment (e.g. A/B) models uncertainty at a subtype boundary: a small stretch of the genome where
    the transition between two flanking subtypes is ambiguous. Accordingly, compound segments are treated as a
    distinct layer on top of the regular (pure) segments:
      - compound_prob   : Bernoulli probability that a given internal breakpoint gets a compound zone
      - compound_lengths: lengths of these zones, fitted as a log-normal (expected to be short)
    Compound segments are excluded from the regular segment-length distribution so the two are not confounded.

    Minimum segment length
    Breakpoint positions are drawn subject to a minimum inter-breakpoint gap derived from the observed minimum
    pure segment length in the real data.  This prevents biologically implausible 1 nt segments from being
    generated by the uniform breakpoint placement step.

Option 2: Blueprint replay — use real CRF architectures as-is.
          Preserves biological realism but limits to known recombination patterns.
"""

import json
import numpy as np
import pandas as pd
from scipy import stats
import argparse
from tqdm import tqdm

workspace_path = "/workspaces/mpath/oanoufa"

# Retrieve n_bp from cmd line
parser = argparse.ArgumentParser(description='Generate CRF blueprints from real data.')
parser.add_argument('--n_bp', type=int, default=5000,
                    help='Number of blueprints to generate for Option 1')
parser.add_argument("--acz", action='store_true', help="Whether to put compound zones or not.")
parser.add_argument('--seed', type=int, default=42,
                    help='Random seed for reproducibility')
args = parser.parse_args()
n_bp_gen = args.n_bp
add_compound_zones = args.acz
seed = args.seed

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fit_lognormal(lengths: pd.Series) -> dict:
    """Fit a log-normal to a Series of positive lengths and return parameters."""
    lengths = lengths.dropna().astype(float)
    lengths = lengths[lengths > 0]
    mu_log  = float(np.log(lengths).mean())
    std_log = float(np.log(lengths).std())
    return {
        'distribution': 'lognormal',
        'mu_log':  mu_log,
        'std_log': std_log,
        'min':     int(lengths.min()),
        'max':     int(lengths.max()),
        'median':  float(lengths.median()),
        'n':       int(len(lengths)),
    }


def _print_lognormal(label: str, d: dict) -> None:
    print(f"  {label:35s}  n={d['n']}  median={d['median']:.0f} bp  "
          f"log-normal(μ={d['mu_log']:.2f}, σ={d['std_log']:.2f})  "
          f"[{d['min']}, {d['max']}]")


def _place_breakpoints(
    n_bp: int,
    genome_start: int,
    genome_end: int,
    min_seg_len: int,
    rng: np.random.Generator,
) -> list:
    """
    Sample `n_bp` breakpoint positions on [genome_start, genome_end] such that
    every resulting segment (including the two flanking ones) is at least
    `min_seg_len` nt long.

    Uses the stars-and-bars trick: reduce the usable span by the minimum
    padding required for n_bp+1 segments, sample uniformly in the reduced
    space, then map back.

    If the genome is too short to fit `n_bp` breakpoints with the minimum
    gap, the number of breakpoints is silently reduced to the maximum
    feasible value.
    """
    span = genome_end - genome_start
    # n_bp breakpoints create n_bp+1 segments, each needing min_seg_len nt.
    # After reserving that minimum, the remaining slack is distributed freely.
    max_bp = max(0, (span // min_seg_len) - 1)
    n_bp   = min(n_bp, max_bp)

    if n_bp == 0:
        return []

    reduced_span = span - (n_bp + 1) * min_seg_len
    # Draw n_bp offsets from [0, reduced_span] without replacement, sort them
    raw = sorted(rng.choice(np.arange(0, reduced_span + 1), size=n_bp, replace=False).tolist())
    # Map back: i-th breakpoint = genome_start + raw[i] + (i+1)*min_seg_len
    breakpoints = [genome_start + raw[i] + (i + 1) * min_seg_len for i in range(n_bp)]
    return breakpoints


# ---------------------------------------------------------------------------
# Option 1 — parameter inference
# ---------------------------------------------------------------------------

def infer_params_option1(df_seg: pd.DataFrame, df_bp: pd.DataFrame) -> dict:
    """
    Option 1: infer generative parameters from real CRF structures.

    Parameters inferred
    -------------------
    n_breakpoints       : distribution of number of *pure* breakpoints per CRF
                          (fitted as a negative binomial)
    segment_lengths     : distribution of *pure* (non-compound) segment lengths
                          (fitted as a log-normal — diagnostic only, not used in generation)
    min_seg_len         : minimum pure segment length observed in the real data;
                          used as the hard lower bound when placing breakpoints
    n_subtypes          : distribution of distinct subtypes per CRF
                          (empirical PMF — small discrete range)
    compound_prob       : probability that a given internal breakpoint gets a
                          flanking compound zone (Bernoulli)
    compound_lengths    : distribution of compound-zone lengths
                          (fitted as a log-normal)

    Compound segments are treated as breakpoint-uncertainty zones inserted
    between two pure segments, so they are excluded from the regular segment
    length distribution.
    """
    params = {}

    # ------------------------------------------------------------------ #
    # Split df_seg into pure and compound rows                            #
    # ------------------------------------------------------------------ #
    is_compound_mask = df_seg['subtype'].str.contains('/', regex=False)
    df_pure     = df_seg[~is_compound_mask].copy()
    df_compound = df_seg[ is_compound_mask].copy()

    # ------------------------------------------------------------------ #
    # Number of breakpoints per CRF                                       #
    # Count only pure segments; compound zones sit *between* pure ones    #
    # and are not counted as independent segments for this distribution.  #
    # n_breakpoints = n_pure_segments - 1                                 #
    # ------------------------------------------------------------------ #
    n_pure_per_crf = df_pure.groupby('crf').size()
    n_bp_per_crf   = (n_pure_per_crf - 1).clip(lower=0)

    mu  = n_bp_per_crf.mean()
    var = n_bp_per_crf.var()

    if var > mu:
        r_nb = mu**2 / (var - mu)
        p_nb = mu / var
    else:
        # Variance ≤ mean → degenerate toward Poisson
        r_nb = 1e6
        p_nb = mu / (mu + 1)

    params['n_breakpoints'] = {
        'distribution': 'negative_binomial',
        'r': r_nb,
        'p': p_nb,
        'empirical_mean': mu,
        'empirical_var':  var,
        'empirical_counts': n_bp_per_crf.value_counts().sort_index().to_dict(),
    }

    # ------------------------------------------------------------------ #
    # Segment lengths — pure segments only (diagnostic)                   #
    # Also derive min_seg_len for constrained breakpoint placement.       #
    # ------------------------------------------------------------------ #
    pure_lengths = df_pure['length'].dropna().astype(float)
    pure_lengths = pure_lengths[pure_lengths > 0]
    params['segment_lengths'] = _fit_lognormal(pure_lengths)
    params['min_seg_len'] = int(pure_lengths.min())

    # ------------------------------------------------------------------ #
    # Number of distinct subtypes per CRF (from pure segments)            #
    # ------------------------------------------------------------------ #
    n_subtypes_per_crf = df_pure.groupby('crf')['subtype'].nunique()
    pmf = n_subtypes_per_crf.value_counts(normalize=True).sort_index()
    params['n_subtypes'] = {
        'distribution': 'empirical',
        'values':       pmf.index.tolist(),
        'probs':        pmf.values.tolist(),
    }

    # ------------------------------------------------------------------ #
    # Compound zones                                                       #
    #                                                                     #
    # compound_prob : fraction of internal breakpoints that have a        #
    #                 compound zone.  Denominator = total internal         #
    #                 breakpoints across all CRFs = sum(n_pure - 1).      #
    # compound_lengths : log-normal fit on compound segment lengths.      #
    # ------------------------------------------------------------------ #
    n_internal_bp_total = int(n_bp_per_crf.sum())
    n_compound_total    = len(df_compound)

    compound_prob = (n_compound_total / n_internal_bp_total
                     if n_internal_bp_total > 0 else 0.0)
    params['compound_prob'] = float(compound_prob)
    params['compound_lengths'] = _fit_lognormal(df_compound['length'])

    # ------------------------------------------------------------------ #
    # Genome start and end boundaries                                    #
    # ------------------------------------------------------------------ #
    # The true start of a CRF is the minimum start position of its segments
    # The true end is the maximum end position of its segments
    crf_starts = df_seg.groupby('crf')['start'].min()
    crf_ends   = df_seg.groupby('crf')['end'].max()

    start_pmf = crf_starts.value_counts(normalize=True).sort_index()
    end_pmf   = crf_ends.value_counts(normalize=True).sort_index()

    params['genome_start'] = {
        'distribution': 'empirical',
        'values': start_pmf.index.astype(int).tolist(),
        'probs':  start_pmf.values.tolist(),
    }
    
    params['genome_end'] = {
        'distribution': 'empirical',
        'values': end_pmf.index.astype(int).tolist(),
        'probs':  end_pmf.values.tolist(),
    }

    # ------------------------------------------------------------------ #
    # Print summary                                                        #
    # ------------------------------------------------------------------ #
    print("\n  === Option 1 parameters ===")
    print(f"  Pure breakpoints/CRF  mean={mu:.1f}  var={var:.1f}  "
          f"(NegBin r={r_nb:.2f} p={p_nb:.3f})")
    print(f"  Min pure segment length (min_seg_len): {params['min_seg_len']} bp")
    _print_lognormal("Pure segment lengths (diag.)", params['segment_lengths'])
    _print_lognormal("Compound zone lengths",         params['compound_lengths'])
    print(f"  Compound prob per internal breakpoint: {compound_prob:.3f}  "
          f"({n_compound_total}/{n_internal_bp_total})")
    print(f"  Distinct subtypes per CRF:\n{pmf.to_string()}")

    return params


# ---------------------------------------------------------------------------
# Option 1 — blueprint sampling
# ---------------------------------------------------------------------------

def sample_blueprint_option1(
    params: dict,
    rng: np.random.Generator = None,
) -> list:
    """
    Sample a novel blueprint from the inferred generative parameters.

    The procedure is:
      1. Sample number of pure breakpoints from the negative binomial.
      2. Sample breakpoint positions subject to a minimum inter-breakpoint gap
         of `min_seg_len` nt (derived from the observed minimum pure segment
         length), so that no pure segment shorter than that can be generated.
      3. Assign subtypes to pure segments.
      4. For each internal breakpoint, with probability compound_prob, insert
         a compound zone of sampled length carved from the right edge of the
         left pure segment.  The compound zone borrows from the pure segment
         so the total genome span is preserved.

    Returns a list of (start, end, subtype_id_list) with local integer
    subtype IDs. The generator remaps these to real subtypes at call time.
    """
    if rng is None:
        rng = np.random.default_rng()

    min_seg_len = params.get('min_seg_len', 1)

    # 1. Sample genome boundaries
    # start_vals  = params['genome_start']['values']
    # start_probs = params['genome_start']['probs']
    # genome_start = int(rng.choice(start_vals, p=start_probs))

    # end_vals    = params['genome_end']['values']
    # end_probs   = params['genome_end']['probs']
    # genome_end   = int(rng.choice(end_vals, p=end_probs))

    # In the end we want to generate full-length CRFs that span the entire genome
    genome_start = 1
    genome_end = 9719

    # Sanity check: Ensure valid boundaries (fallback to HXB2 bounds just in case)
    if genome_start >= genome_end:
        genome_start, genome_end = 1, 9719
    # 1. Sample number of pure breakpoints
    nb = params['n_breakpoints']
    n_bp = int(rng.negative_binomial(nb['r'], nb['p']))
    n_bp = max(1, n_bp)

    # 2. Place breakpoints with minimum-gap constraint
    bp_positions = _place_breakpoints(n_bp, genome_start, genome_end, min_seg_len, rng)

    # 3. Build pure segments
    boundaries = [genome_start] + bp_positions + [genome_end]
    n_segments  = len(boundaries) - 1

    # 4. Assign subtypes
    n_st_vals  = params['n_subtypes']['values']
    n_st_probs = params['n_subtypes']['probs']
    n_subtypes = int(rng.choice(n_st_vals, p=n_st_probs))
    n_subtypes = max(1, min(n_subtypes, n_segments))

    base_ids = list(range(n_subtypes))
    if n_segments > n_subtypes:
        base_ids += rng.integers(0, n_subtypes, size=n_segments - n_subtypes).tolist()
    rng.shuffle(base_ids)

    # 5. Build the blueprint with optional compound zones at breakpoints
    cl    = params['compound_lengths']
    cprob = params['compound_prob']

    blueprint = []
    for i in range(n_segments):
        seg_start = boundaries[i]
        seg_end   = boundaries[i + 1]
        left_id   = base_ids[i]
        right_id  = base_ids[i + 1] if i + 1 < n_segments else None

        # Insert compound zone with probability cprob if this is an internal breakpoint long enough
        insert_compound = (
            right_id is not None
            and right_id != left_id       # real subtype boundary
            and (seg_end - seg_start) >= min_seg_len*2  # enough room to carve out a compound zone
            and rng.random() < cprob
        )

        if insert_compound and add_compound_zones:
            # Sample compound-zone length from the log-normal
            raw_len = int(np.round(rng.lognormal(cl['mu_log'], cl['std_log'])))
            # Clamp: at most half the current pure segment, leaving at least 1 nt pure
            max_cz  = max(1, (seg_end - seg_start) // 2)
            cz_len  = max(1, min(raw_len, max_cz))

            pure_end = seg_end - cz_len
            if pure_end > seg_start:
                blueprint.append((seg_start, pure_end, [left_id]))
                blueprint.append((pure_end,  seg_end,  [left_id, right_id]))
            else:
                # Segment too short to split — label whole thing compound
                blueprint.append((seg_start, seg_end, [left_id, right_id]))
        else:
            blueprint.append((seg_start, seg_end, [left_id]))

    return blueprint


# ---------------------------------------------------------------------------
# Option 1 — distribution comparison (real vs generated)
# ---------------------------------------------------------------------------

def compare_distributions_option1(
    params: dict,
    df_seg: pd.DataFrame,
    n_generated: int = 200,
    rng: np.random.Generator = None,
) -> None:
    """
    Generate `n_generated` blueprints from Option 1 and compare ALL inferred
    distributions against the real data side by side:

      - n_breakpoints per CRF    (NegBin; one integer per CRF)
      - n_subtypes per CRF       (empirical PMF; one integer per CRF)
      - pure segment lengths      (log-normal; one value per pure segment)
      - compound zone lengths     (log-normal; one value per compound zone)
    """
    if rng is None:
        rng = np.random.default_rng()

    # Collect generated statistics
    gen_starts      = []
    gen_ends        = []
    n_bp_gen         = []
    n_st_gen         = []
    pure_len_gen     = []
    compound_len_gen = []

    for _ in range(n_generated):
        bp = sample_blueprint_option1(params, rng=rng)

        gen_starts.append(bp[0][0])
        gen_ends.append(bp[-1][1])

        pure_segs     = [(s, e, ids) for s, e, ids in bp if len(ids) == 1]
        compound_segs = [(s, e, ids) for s, e, ids in bp if len(ids) > 1]

        n_bp_gen.append(len(pure_segs) - 1)
        st_ids = {sid for _, _, ids in bp for sid in ids}
        n_st_gen.append(len(st_ids))

        pure_len_gen.extend(e - s for s, e, _ in pure_segs)
        compound_len_gen.extend(e - s for s, e, _ in compound_segs)

    # Real data
    real_starts = df_seg.groupby('crf')['start'].min()
    real_ends   = df_seg.groupby('crf')['end'].max()
    is_compound_mask  = df_seg['subtype'].str.contains('/', regex=False)
    df_pure           = df_seg[~is_compound_mask]
    df_compound       = df_seg[ is_compound_mask]

    n_pure_per_crf    = df_pure.groupby('crf').size()
    n_bp_real         = (n_pure_per_crf - 1).clip(lower=0)
    n_subtypes_real   = df_pure.groupby('crf')['subtype'].nunique()
    pure_len_real     = df_pure['length'].dropna().astype(float)
    pure_len_real     = pure_len_real[pure_len_real > 0]
    compound_len_real = df_compound['length'].dropna().astype(float)
    compound_len_real = compound_len_real[compound_len_real > 0]

    # ------------------------------------------------------------------ #
    # Printing helpers                                                     #
    # ------------------------------------------------------------------ #
    W_LABEL = 30
    W_COL   = 12

    def _header(title: str) -> None:
        print(f"\n  -- {title} --")
        print(f"  {'':>{W_LABEL}}  {'real':>{W_COL}}  {'generated':>{W_COL}}")
        print(f"  {'-' * (W_LABEL + 2 * W_COL + 4)}")

    def _row(label: str, real_val, gen_val, fmt: str = '.1f') -> None:
        def _fmt(v):
            if v is None or (isinstance(v, float) and np.isnan(v)):
                return 'n/a'.rjust(W_COL)
            return format(v, fmt).rjust(W_COL)
        print(f"  {label:>{W_LABEL}}  {_fmt(real_val)}  {_fmt(gen_val)}")

    def _continuous_block(label: str, real_s: pd.Series, gen_list: list) -> None:
        """Descriptive stats + log-normal fit for a continuous length distribution."""
        _header(label)
        gen_s = pd.Series(gen_list, dtype=float)
        gen_s = gen_s[gen_s > 0]
        r, g  = real_s, gen_s

        _row('n',            len(r),          len(g),          fmt='d')
        _row('min (bp)',     r.min()    if len(r) else float('nan'), g.min()    if len(g) else float('nan'))
        _row('median (bp)',  r.median() if len(r) else float('nan'), g.median() if len(g) else float('nan'))
        _row('mean (bp)',    r.mean()   if len(r) else float('nan'), g.mean()   if len(g) else float('nan'))
        _row('std (bp)',     r.std()    if len(r) else float('nan'), g.std()    if len(g) else float('nan'))
        _row('max (bp)',     r.max()    if len(r) else float('nan'), g.max()    if len(g) else float('nan'))
        if len(r) > 1 and len(g) > 1:
            _row('log-normal μ', np.log(r).mean(), np.log(g).mean(), fmt='.3f')
            _row('log-normal σ', np.log(r).std(),  np.log(g).std(),  fmt='.3f')

    def _discrete_block(label: str, real_s: pd.Series, gen_list: list) -> None:
        """Mean/std + full PMF comparison for a discrete per-CRF distribution."""
        _header(label)
        gen_s = pd.Series(gen_list, dtype=int)
        r, g  = real_s, gen_s

        _row('n (CRFs)', len(r),    len(g),    fmt='d')
        _row('mean',     r.mean(),  g.mean())
        _row('std',      r.std(),   g.std())
        _row('min',      r.min(),   g.min(),   fmt='.0f')
        _row('max',      r.max(),   g.max(),   fmt='.0f')

        # Full PMF
        all_vals = sorted(set(r.tolist()) | set(g.tolist()))
        real_pmf = r.value_counts(normalize=True)
        gen_pmf  = g.value_counts(normalize=True)
        print(f"\n  {'value':>{W_LABEL}}  {'real (%)':>{W_COL}}  {'gen (%)':>{W_COL}}")
        for v in all_vals:
            _row(str(v), real_pmf.get(v, 0.0) * 100, gen_pmf.get(v, 0.0) * 100, fmt='.1f')

    # ------------------------------------------------------------------ #
    # Print all four comparisons                                          #
    # ------------------------------------------------------------------ #
    print(f"\n  === Distribution comparison: real vs {n_generated} generated CRFs ===")
    _discrete_block('Genome Start Position', real_starts, gen_starts)
    _discrete_block('Genome End Position',   real_ends,   gen_ends)
    _discrete_block('n_breakpoints per CRF',   n_bp_real,        n_bp_gen)
    _discrete_block('n_subtypes per CRF',       n_subtypes_real,  n_st_gen)
    _continuous_block('pure segment lengths',   pure_len_real,    pure_len_gen)
    print("\n  Note: compound zones are optional and may be disabled to simplify the model, they are currently " + ("enabled." if add_compound_zones else "disabled."))
    _continuous_block('compound zone lengths',  compound_len_real, compound_len_gen)


# ---------------------------------------------------------------------------
# Option 2 — blueprint replay
# ---------------------------------------------------------------------------

def build_blueprints_option2(df_seg: pd.DataFrame) -> list:
    """
    Option 2: encode each real CRF structure as a blueprint.
    Blueprints are lists of (start, end, subtype_id_list) where
    subtype IDs are local per-blueprint integers (so the generator
    can remap them to any real subtype at generation time).
    """
    all_blueprints = []
    for crf, group in df_seg.groupby('crf', sort=False):
        subtype_id_dict = {}
        blueprint = []
        for _, row in group.iterrows():
            subtypes = row['subtype'].split('/') if '/' in row['subtype'] else [row['subtype']]
            for st in subtypes:
                if st not in subtype_id_dict:
                    subtype_id_dict[st] = len(subtype_id_dict)
            blueprint.append((row['start'], row['end'], [subtype_id_dict[st] for st in subtypes]))
        all_blueprints.append(blueprint)
    return all_blueprints


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    df_bp  = pd.read_csv(f"{workspace_path}/data/LANL/crf/lanl_crf_breakpoints.csv")
    df_seg = pd.read_csv(f"{workspace_path}/data/LANL/crf/lanl_crf_segments.csv")

    # Option 1: generative parameters
    params_option1 = infer_params_option1(df_seg, df_bp)

    with open(f"{workspace_path}/data/LANL/crf/params_option1.json", 'w') as f:
        json.dump(params_option1, f)

    # Sanity check: sample a few blueprints and print them
    rng = np.random.default_rng(seed)
    print("\nOption 1 blueprints:")
    blueprints_option1 = []
    for _ in tqdm(range(n_bp_gen), desc="Sampling blueprints...", mininterval=30):
        bp = sample_blueprint_option1(params_option1,
                                      rng=rng)
        blueprints_option1.append(bp)

    # Full distribution comparison: real vs generated CRFs
    compare_distributions_option1(params_option1, df_seg, n_generated=n_bp_gen, rng=rng)
    file_name = f"{workspace_path}/data/LANL/crf/synthetic_blueprints_{n_bp_gen}_{'acz' if add_compound_zones else 'no_acz'}.json"
    with open(file_name, 'w') as f:
        json.dump(blueprints_option1, f)

    # Option 2: existing CRF blueprints
    blueprints_option2 = build_blueprints_option2(df_seg)
    print(f"\nOption 2 blueprints: {len(blueprints_option2)}")

    with open(f"{workspace_path}/data/LANL/crf/real_blueprints.json", 'w') as f:
        json.dump(blueprints_option2, f)